// Generates lib/features/avatar/data/asset_catalog.g.dart from sprites/.
//
// Run from the project root:  dart run tool/gen_catalog.dart
//
// Scans the sprite folders, reads each PNG's intrinsic size (needed for
// anchored layering in AvatarPreview), and emits a const Dart catalog.
// Item names/rarities below were hand-assigned from sprites/_qa_items.png.

import 'dart:io';

import 'package:image/image.dart' as img;

const _outPath = 'lib/features/avatar/data/asset_catalog.g.dart';

/// Hand-assigned names for sprites/items/item_001..084 (QA-sheet order).
const _itemNames = [
  "Squire's Sword", "Knight's Blade", "Chef's Knife", 'Shadow Dagger',
  'Frost Blade', 'Oak Staff', 'Red Rose', 'Carrot', 'Star Wand',
  'Sapphire Scepter', 'Amethyst Scepter', 'Moonvine Staff', 'Bubble Tea',
  'Swirl Lollipop',
  "Hunter's Bow", 'Vine Bow', 'Ribbon Bow', 'Crossbow', 'Slingshot',
  'Fishing Rod', 'Butterfly Net', 'Black Umbrella', 'Lace Parasol',
  'Iron Lantern', 'Torch', 'Paper Kite', 'Balloon Puppy', 'Skateboard',
  'Old Tome', 'Moon Tome', 'Leaf Tome', 'Gem Tome', 'Heart Tome',
  'Retro Console', 'Flip Phone', 'Teddy Bear', 'Bunny Plush', 'Cat Plush',
  'Shiba Plush', 'Rubber Duck', 'Snow Globe', 'Music Box',
  'Heart Wand', 'Charm Wand', 'Candy Cane', 'Pinwheel', 'Sunflower',
  'Cotton Candy', 'Sparkler', 'Glow Stick', 'Pink Balloon', 'Star Balloon',
  'Paw Wand', 'Disco Ball', 'Retro Camera', 'Boombox',
  'Pickaxe', 'Woodcutter Axe', 'Shovel', 'Sickle', 'Sledgehammer',
  'Shuriken', 'Nunchucks', 'Spiked Flail', 'Wrench', 'Quest Scroll Kit',
  'Green Elixir', 'Spray Can', 'Megaphone', 'Microphone',
  'Bubble Blower', 'Potted Cactus', 'Aloe Plant', 'Coffee To-Go',
  'Sprout Pouch', 'Watering Can', 'Soft Serve', 'Taiyaki', 'Jar & Ukulele',
  'Pink Guitar', 'Violin', 'Tambourine', 'Pan Flute', 'Sparrow',
];

/// Hand-assigned rarity per item (same order). c/u/r/e/l shorthand.
const _itemRarities =
    'c u c e l c u c r e e l u u '
    'c u r r c u c u r u c u r r '
    'c r u e r e u u u u r c e l '
    'r e c c c u r c c u r l r e '
    'c c c u u r r e c r u u u r '
    'u c c c u c u u e r e u r l';

const _rarityNames = {
  'c': 'common',
  'u': 'uncommon',
  'r': 'rare',
  'e': 'epic',
  'l': 'legendary',
};

const _rarityPrices = {
  'common': 40,
  'uncommon': 90,
  'rare': 180,
  'epic': 320,
  'legendary': 600,
};

const _styles = {
  'modern_feminine': 'Modern F',
  'modern_masculine': 'Modern M',
  'rpg_feminine': 'RPG F',
  'rpg_neutral': 'RPG N',
};

/// Dropped from the catalog: too close in color to a kept eye sprite
/// (aqua/teal cover the cyans, blue covers royal_blue, purple covers violet,
/// pink/magenta cover rose). Files stay on disk but aren't offered.
const _excludedEyes = {
  'cyan', 'turquoise', 'ice_blue', 'royal_blue', 'violet', 'rose',
};

/// The 112 hair sprites are 8 styles x 14 colors, cycling every 14 files.
/// Verified against _qa_hair.png + per-sprite average HSL. Offsets 7/8 vary
/// by style (gray/silver in early styles, brown/blonde in later ones), so
/// those use the measured split.
String _hairColor(int n) {
  final offset = (n - 1) % 14 + 1;
  switch (offset) {
    case 1:
      return 'black';
    case 2:
    case 3:
      return 'brown';
    case 4:
    case 5:
      return 'blonde';
    case 6:
    case 14:
      return 'red';
    case 7:
      return n == 7 ? 'silver' : 'brown';
    case 8:
      return const {78, 92, 106}.contains(n) ? 'blonde' : 'silver';
    case 9:
      return 'purple';
    case 10:
      return 'blue';
    case 11:
      return 'green';
    case 12:
      return 'pink';
    default:
      return 'orange';
  }
}

void main() {
  final out = StringBuffer('''
// GENERATED by tool/gen_catalog.dart — do not edit by hand.
// Regenerate after changing sprites/:  dart run tool/gen_catalog.dart

/// A drawable sprite with its intrinsic pixel size (used for layer anchoring).
class SpriteAsset {
  final String id;
  final String name;
  final String asset;
  final int w;
  final int h;

  const SpriteAsset(this.id, this.name, this.asset, this.w, this.h);
}

class HairAsset extends SpriteAsset {
  /// Color-group key, e.g. 'black', 'blonde' (see kHairColorLabels).
  final String color;

  const HairAsset(super.id, super.name, super.asset, super.w, super.h,
      this.color);
}

class ClothingAsset extends SpriteAsset {
  /// 'top' or 'bottom'.
  final String slot;

  /// Style-set key, e.g. 'modern_feminine'.
  final String style;
  final String rarity;

  /// Opaque-pixel bounding box within the sprite (the garment itself,
  /// excluding transparent padding). Used to anchor the garment on the body.
  final int contentL;
  final int contentT;
  final int contentW;
  final int contentH;

  /// Extra horizontal stretch (>= 1.0) so the garment covers the base body's
  /// flared arms/legs where the garment claims to cover them. The garment
  /// sheets were drawn for a slimmer template than the chibi body, so
  /// sleeved tops and pants need widening or skin pokes out at the sides;
  /// fitted pieces (tanks, corsets) stay at 1.0. Computed against the body
  /// silhouette at generation time — see _fitWidthScale in gen_catalog.dart.
  final double fitWidthScale;

  const ClothingAsset(super.id, super.name, super.asset, super.w, super.h,
      this.slot, this.style, this.rarity,
      this.contentL, this.contentT, this.contentW, this.contentH,
      this.fitWidthScale);
}

class ItemAsset extends SpriteAsset {
  final String rarity;
  final int priceCoins;

  const ItemAsset(super.id, super.name, super.asset, super.w, super.h,
      this.rarity, this.priceCoins);
}

/// Display labels for the clothing style sets.
const Map<String, String> kStyleLabels = {
''');
  _styles.forEach((k, v) => out.writeln("  '$k': '$v',"));
  out.writeln('};\n');

  out.writeln('''
/// Hair color-group display order and labels.
const Map<String, String> kHairColorLabels = {
  'black': 'Black',
  'brown': 'Brown',
  'blonde': 'Blonde',
  'red': 'Red',
  'orange': 'Orange',
  'silver': 'Silver',
  'purple': 'Purple',
  'blue': 'Blue',
  'green': 'Green',
  'pink': 'Pink',
};
''');

  _emitSprites(out, 'kSkinTones', 'sprites/avatars/skin_tones', 'skin');
  _emitSprites(out, 'kEyeColors', 'sprites/eyes', 'eyes');
  _emitHair(out);
  _emitClothes(out);
  _emitItems(out);

  File(_outPath).writeAsStringSync(out.toString());
  stdout.writeln('Wrote $_outPath');
}

void _emitSprites(StringBuffer out, String listName, String dir, String kind) {
  out.writeln('const List<SpriteAsset> $listName = [');
  for (final f in _pngs(dir)) {
    final base = _baseName(f);
    if (kind == 'eyes' && _excludedEyes.contains(base)) continue;
    final (w, h) = _pngSize(f);
    out.writeln("  SpriteAsset('${kind}_$base', '${_humanize(base)}', "
        "'${_assetPath(f)}', $w, $h),");
  }
  out.writeln('];\n');
}

void _emitHair(StringBuffer out) {
  out.writeln('const List<HairAsset> kHairStyles = [');
  for (final f in _pngs('sprites/hair')) {
    final base = _baseName(f);
    final n = int.parse(base.split('_').last);
    final (w, h) = _pngSize(f);
    out.writeln("  HairAsset('$base', 'Style $n', '${_assetPath(f)}', "
        "$w, $h, '${_hairColor(n)}'),");
  }
  out.writeln('];\n');
}

void _emitClothes(StringBuffer out) {
  out.writeln('const List<ClothingAsset> kClothes = [');
  for (final style in _styles.keys) {
    for (final slotDir in ['tops', 'bottoms']) {
      final slot = slotDir == 'tops' ? 'top' : 'bottom';
      for (final rarityDir in ['common', 'uncommon', 'rare_epic']) {
        final dir = 'sprites/clothes/$style/$slotDir/$rarityDir';
        for (final f in _pngs(dir)) {
          final base = _baseName(f);
          final n = int.parse(base.split('_').last);
          // rare_epic folders alternate deterministically: odd=rare, even=epic.
          final rarity = rarityDir == 'rare_epic'
              ? (n.isOdd ? 'rare' : 'epic')
              : rarityDir;
          final id = '${style}_${slot}_$base';
          final label = _styles[style]!;
          final name =
              '$label ${slot == 'top' ? 'Top' : 'Bottom'} ${n.toString().padLeft(2, '0')}';
          final (w, h) = _pngSize(f);
          final (cl, ct, cw, ch) = _contentBox(f);
          final fit = _fitWidthScale(f, slot);
          out.writeln(
              "  ClothingAsset('$id', '$name', '${_assetPath(f)}', $w, $h, "
              "'$slot', '$style', '$rarity', $cl, $ct, $cw, $ch, $fit),");
        }
      }
    }
  }
  out.writeln('];\n');
}

void _emitItems(StringBuffer out) {
  final rarities = _itemRarities.split(RegExp(r'\s+'));
  final files = _pngs('sprites/items');
  if (files.length != _itemNames.length || rarities.length != files.length) {
    throw StateError('items: ${files.length} files, ${_itemNames.length} '
        'names, ${rarities.length} rarities — counts must match');
  }
  out.writeln('const List<ItemAsset> kItems = [');
  for (var i = 0; i < files.length; i++) {
    final f = files[i];
    final rarity = _rarityNames[rarities[i]]!;
    final price = _rarityPrices[rarity]!;
    final (w, h) = _pngSize(f);
    final name = _itemNames[i].replaceAll("'", r"\'");
    out.writeln("  ItemAsset('${_baseName(f)}', '$name', '${_assetPath(f)}', "
        "$w, $h, '$rarity', $price),");
  }
  out.writeln('];');
}

List<File> _pngs(String dir) {
  final files = Directory(dir)
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.png'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));
  if (files.isEmpty) throw StateError('no PNGs found in $dir');
  return files;
}

String _assetPath(File f) => f.path.replaceAll(r'\', '/');

String _baseName(File f) =>
    f.uri.pathSegments.last.replaceAll('.png', '');

String _humanize(String s) => s
    .split('_')
    .map((w) => '${w[0].toUpperCase()}${w.substring(1)}')
    .join(' ');

/// The base body silhouette (any skin tone — they share one outline), used
/// to compute per-garment fit widening. Row spans are in body-canvas pixels.
class _BodySpans {
  static late final List<int> full = _spans(0, 141);
  // Legs only: x-window excludes the fists hanging beside the hips.
  static late final List<int> legs = _spans(30, 111);

  static List<int> _spans(int x0, int x1) {
    final im = img.decodePng(
        File('sprites/avatars/skin_tones/light.png').readAsBytesSync())!;
    return List.generate(im.height, (y) {
      int minX = -1, maxX = -1;
      for (var x = x0; x < x1 && x < im.width; x++) {
        if (im.getPixel(x, y).a > 10) {
          if (minX < 0) minX = x;
          maxX = x;
        }
      }
      return minX < 0 ? 0 : maxX - minX + 1;
    });
  }
}

/// How much wider (>= 1.0) a garment must render so the body doesn't poke
/// out at the sides. Mirrors AvatarPreview's layout: garments are placed at
/// scale 1.30 with tops hung from y=124 and bottoms from y=182. For each
/// garment row, if the garment claims coverage there but is narrower than
/// the body, the deficit sets the widening factor:
///  - tops: body rows 162-198 (upper arms through wrists); only rows where
///    the garment already extends past the torso (>= 85px scaled) count, so
///    tanks and other fitted pieces stay untouched.
///  - bottoms: body rows 218-262 (legs above the feet).
/// Garment row spans use a rolling max (+-3 rows) so thin detail rows
/// (belts, drawstrings) don't inflate the factor.
double _fitWidthScale(File f, String slot) {
  const scale = 1.30;
  final anchor = slot == 'top' ? 124 : 182;
  final im = img.decodePng(f.readAsBytesSync())!;
  final spans = List.generate(im.height, (y) {
    int minX = -1, maxX = -1;
    for (var x = 0; x < im.width; x++) {
      if (im.getPixel(x, y).a > 10) {
        if (minX < 0) minX = x;
        maxX = x;
      }
    }
    return minX < 0 ? 0 : maxX - minX + 1;
  });
  final contentTop = spans.indexWhere((s) => s > 0);
  var fit = 1.0;
  for (var r = contentTop; r < im.height; r++) {
    if (spans[r] == 0) continue;
    var smoothed = 0;
    for (var rr = r - 3; rr <= r + 3; rr++) {
      if (rr >= 0 && rr < im.height && spans[rr] > smoothed) {
        smoothed = spans[rr];
      }
    }
    final g = smoothed * scale;
    final y = (anchor + (r - contentTop) * scale).round();
    if (y < 0 || y >= _BodySpans.full.length) continue;
    final int req;
    if (slot == 'top') {
      if (y < 162 || y > 198 || g < 85) continue;
      req = _BodySpans.full[y] + 4;
    } else {
      if (y < 218 || y > 262) continue;
      req = _BodySpans.legs[y] + 4;
    }
    if (g < req && req / g > fit) fit = req / g;
  }
  final cap = slot == 'top' ? 1.45 : 1.30;
  return double.parse((fit > cap ? cap : fit).toStringAsFixed(3));
}

/// Bounding box of pixels with alpha > 10 (left, top, width, height).
/// This is the garment itself minus the transparent padding, which varies
/// per sprite — AvatarPreview anchors garments on the body by this box.
(int, int, int, int) _contentBox(File f) {
  final im = img.decodePng(f.readAsBytesSync())!;
  int minX = im.width, minY = im.height, maxX = -1, maxY = -1;
  for (final p in im) {
    if (p.a > 10) {
      if (p.x < minX) minX = p.x;
      if (p.x > maxX) maxX = p.x;
      if (p.y < minY) minY = p.y;
      if (p.y > maxY) maxY = p.y;
    }
  }
  if (maxX < 0) throw StateError('fully transparent sprite: ${f.path}');
  return (minX, minY, maxX - minX + 1, maxY - minY + 1);
}

/// Reads width/height from the PNG IHDR chunk (bytes 16..23, big-endian).
(int, int) _pngSize(File f) {
  final b = f.openSync().readSync(24);
  int be(int o) => (b[o] << 24) | (b[o + 1] << 16) | (b[o + 2] << 8) | b[o + 3];
  return (be(16), be(20));
}
